steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web-dashboard/Dockerfile
      - -t
      - ${_WEB_IMAGE}
      - --build-arg
      - VITE_API_BASE_URL=${_API_BASE_URL}
      - --build-arg
      - VITE_REDIRECT_BASE_URL=${_REDIRECT_BASE_URL}
      - --build-arg
      - VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}
      - --build-arg
      - VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}
      - .
images:
  - ${_WEB_IMAGE}
